# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/58/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/58/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blazej/workspace/FlappyBird

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blazej/workspace/FlappyBird

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/58/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/58/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blazej/workspace/FlappyBird/CMakeFiles /home/blazej/workspace/FlappyBird/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blazej/workspace/FlappyBird/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlappyBird

# Build rule for target.
FlappyBird: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlappyBird
.PHONY : FlappyBird

# fast build rule for target.
FlappyBird/fast:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/build
.PHONY : FlappyBird/fast

src/arm.o: src/arm.cpp.o

.PHONY : src/arm.o

# target to build an object file
src/arm.cpp.o:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/arm.cpp.o
.PHONY : src/arm.cpp.o

src/arm.i: src/arm.cpp.i

.PHONY : src/arm.i

# target to preprocess a source file
src/arm.cpp.i:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/arm.cpp.i
.PHONY : src/arm.cpp.i

src/arm.s: src/arm.cpp.s

.PHONY : src/arm.s

# target to generate assembly for a file
src/arm.cpp.s:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/arm.cpp.s
.PHONY : src/arm.cpp.s

src/display.o: src/display.cpp.o

.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i

.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s

.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/driver.o: src/driver.cpp.o

.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i

.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s

.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

src/featureDetector.o: src/featureDetector.cpp.o

.PHONY : src/featureDetector.o

# target to build an object file
src/featureDetector.cpp.o:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/featureDetector.cpp.o
.PHONY : src/featureDetector.cpp.o

src/featureDetector.i: src/featureDetector.cpp.i

.PHONY : src/featureDetector.i

# target to preprocess a source file
src/featureDetector.cpp.i:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/featureDetector.cpp.i
.PHONY : src/featureDetector.cpp.i

src/featureDetector.s: src/featureDetector.cpp.s

.PHONY : src/featureDetector.s

# target to generate assembly for a file
src/featureDetector.cpp.s:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/featureDetector.cpp.s
.PHONY : src/featureDetector.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/FlappyBird.dir/build.make CMakeFiles/FlappyBird.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... FlappyBird"
	@echo "... edit_cache"
	@echo "... src/arm.o"
	@echo "... src/arm.i"
	@echo "... src/arm.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
	@echo "... src/featureDetector.o"
	@echo "... src/featureDetector.i"
	@echo "... src/featureDetector.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

